### ISSUE TITLE
Unwanted refresh page in new and edit document-set

### ISSUE THREAD

**Issue by CestFede** [danswer-ai/danswer#1295] opened 2024-04-03 16:00 UTC
Hello, 
I am facing the following issue. 

In the new document-set function (<host>/admin/documents/sets/new), the page refreshes every 8/10 seconds, clearing the data entered in the name and description fields: you have to be very quick to enter a record!  
Idem in the document-set editing function (<host>/admin/documents/sets/<n>).

Thank you.

**Comment by aviadber** [comment] 2024-04-08 06:31
I am also experiencing this

**Comment by CestFede** [comment] 2024-04-25 16:46
The page refresh issue, **which prevents insertion or modification**, is due to the failure of the 
GET call to <host>/api/manage/admin/user-group 
which actually does not exist.
Would you be able to publish it?
Thank you.

**Comment by mowsie2k** [comment] 2024-04-26 23:16
Also experiencing this issue, thank you for adding the cause here. May have to ask on Slack.

**Comment by numberonewastefellow** [comment] 2024-05-01 17:42
I'm also experiencing this issue, while creating document sets

**Comment by zotya** [comment] 2024-05-08 13:23
I have a PR, that solves this problem: #1433

**Comment by Weves** [comment] 2024-05-18 01:12
Hey @zotya @numberonewastefellow @mowsie2k @CestFede @aviadber! This has been fixed in https://github.com/danswer-ai/danswer/pull/1474!

Big shoutout to @zotya for finding the issue and inspiring the final fix 🙇

**Closed by Weves** 2024-05-18 01:12 UTC

**Comment by CestFede** [comment] 2024-05-18 06:15
Thanks Il giorno 18 mag 2024, alle ore 03:12, Chris Weaver ***@***.***> ha scritto:﻿
Hey @zotya @numberonewastefellow @mowsie2k @CestFede @aviadber! This has been fixed in #1474!
Big shoutout to @zotya for finding the issue and inspiring the final fix 🙇
