### ISSUE TITLE
Allow contribution of new Connector implementations

### ISSUE THREAD

**Issue by derklinge** [danswer-ai/danswer#160] opened 2023-07-11 16:50 UTC
Are there any plans to allow contributions of new Connectors, or some other way of contributing to Connector availability?

**Comment by yuhongsun96** [comment] 2023-07-13 01:03
Working on a CONTRIBUTING.md today, will also release the docs as opensource so contributors can also explain the setup for the connector.

**Comment by yuhongsun96** [comment] 2023-07-13 01:15
Marking as duplicate of https://github.com/danswer-ai/danswer/issues/158

**Comment by yuhongsun96** [comment] 2023-07-13 01:15
Thanks for your input!

**Closed by yuhongsun96** 2023-07-13 01:15 UTC
Labels: duplicate

**Comment by derklinge** [comment] 2023-07-14 13:05
Thanks for your quick response, I'm looking forward to it.

**Comment by yuhongsun96** [comment] 2023-07-15 05:26
The CONTRIBUTING.md is out, also the docs are now public so if you happen to contribute a connector, you can also update the docs for getting the access token and setup steps.

If you feel that there is more that needs to be done to make contributing connectors easier, please comment below

**Comment by derklinge** [comment] 2023-07-20 14:53
Thank you very much! I'll provide feedback as soon as possible.
