### ISSUE TITLE
unable to start docker compose - vespa illegal instruction

### ISSUE THREAD

**Issue by perfecto25** [danswer-ai/danswer#3209] opened 2024-11-22 16:05 UTC
nginx and api containers unable to start due to vespa error

```
root@atlas2 /o/d/d/d/docker_compose docker compose -f docker-compose.dev.yml -p danswer-stack up -d --pull always --force-recreate

```

docker logs danswer-stack-index-1

```
/usr/local/bin/start-container.sh: line 67:    10 Illegal instruction     /opt/vespa/bin/vespa-start-configserver
```
running on  Linux atlas2 3.10.0-1160.119.1.el7.x86_64  (centos 7)
docker v 24.0

host is a Dell poweredge rack server, 16 CPU, 190G RAM

**Comment by rkuo-danswer** [comment] 2024-11-22 19:12
Duplicate of https://github.com/danswer-ai/danswer/issues/431

**Closed by rkuo-danswer** 2024-11-22 19:12 UTC

**Comment by perfecto25** [comment] 2024-11-22 19:21
https://github.com/danswer-ai/danswer/issues/431#issuecomment-1986281709
