### ISSUE TITLE
Error logging in when enabling basic authentication

### ISSUE THREAD

**Issue by abbaasi** [danswer-ai/danswer#1139] opened 2024-02-27 11:45 UTC
Good morning
I have set up Danswer locally in dev mode using HTTP connecting to Azure OpenAI and everything works fine. 
When I start enabling basic authentication, it seems that the users are not signed up correctly and hence they won't be able to log in.
Here is my .env file:
```
GEN_AI_MODEL_PROVIDER=azure

GEN_AI_MODEL_VERSION=xxxx # Note that this is the Azure Deployment ID

GEN_AI_API_ENDPOINT=https://xxxxxxx.openai.azure.com/

GEN_AI_API_VERSION=2024-02-15-preview

GEN_AI_API_KEY=xxxxxxxxxxxxxxxxxxxxxxxxxxxx

AUTH_TYPE=basic

```
The signup does not give any message, but it seems the users are registered.
And when logging in, it gives the following error in the console logs:

```
t/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36" "-"
api_server-1 | INFO: 172.18.0.6:36540 - "GET /auth/type HTTP/1.1" 200 OK
api_server-1 | INFO: 172.18.0.6:36548 - "GET /manage/me HTTP/1.1" 403 Forbidden
api_server-1 | INFO: 172.18.0.6:36584 - "GET /secondary-index/get-embedding-models HTTP/1.1" 403 Forbidden
api_server-1 | INFO: 172.18.0.6:36552 - "GET /manage/indexing-status HTTP/1.1" 403 Forbidden
api_server-1 | INFO: 172.18.0.6:36578 - "GET /query/valid-tags HTTP/1.1" 403 Forbidden
api_server-1 | INFO: 172.18.0.6:36566 - "GET /manage/document-set HTTP/1.1" 403 Forbidden
api_server-1 | INFO: 172.18.0.6:36574 - "GET /persona HTTP/1.1" 403 Forbidden
nginx-1 | 151.240.162.111 - - [27/Feb/2024:10:20:07 +0000] "GET /search HTTP/1.1" 200 875 

```

**Comment by regmibijay** [comment] 2024-02-27 21:12
Hi, could it be duplicate of this? https://github.com/danswer-ai/danswer/issues/955

**Comment by abbaasi** [comment] 2024-02-28 13:58
Thanks @regmibijay 
I will check the solutions there

**Comment by regmibijay** [comment] 2024-03-01 07:48
The patch for this was merged, please try with latest images.

**Comment by abbaasi** [comment] 2024-03-01 13:40
Thanks @regmibijay 
I pulled the latest source, rebuilt, and now the authentication works well.
BTW, is there an environment variable to hide "Create an account" link (signup) and how to manage (edit, remove, change password) for users?

**Closed** 2024-03-01 13:40 UTC
